[package]
name = "rustyheadphones"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rodio = "0.19.0"
rustyline-async = "0.4.3"
tokio = {version="1.40.0", features=["full"]}
walkdir = "2.5.0"
rand = "*"
rust_spotify_web_playback_sdk = "0.2.1"
alsa = "0.9.1"
