[package]
name = "rustyheadphones"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rodio = "0.19.0"
rustyline-async = "0.4.3"
tokio = {version="1.40.0", features=["full"]}
walkdir = "2.5.0"
rand = "*"
eframe = "0.24"
egui = "0.24"
rfd = "0.12"
rustyline = "14.0.0"
